package main

import "testing"

func TestScan(t *testing.T) {
	tests := []struct {
		name string
		text string
		hits int
	}{
		{"clean", "feat(sim): add fake clock\n\nTimers fire in deadline order.", 0},
		{"trailer any case", "fix: x\n\nCO-AUTHORED-BY: someone <a@b>", 1},
		{"generated line", "docs: y\n\nGenerated with some tool", 1},
		{"emoji", "chore: z \U0001F916", 1},
		{"protoc header is fine", "// Code generated by protoc-gen-go. DO NOT EDIT.", 0},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := scan("x", tt.text, defaultPatterns); len(got) != tt.hits {
				t.Fatalf("scan = %v, want %d hit(s)", got, tt.hits)
			}
		})
	}
}
